dist: precise

language: php

sudo: false

php:
  - hhvm
  - nightly

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      env: extension='true'
    - php: 5.3
      env: extension='false'
    - php: 5.4
      env: extension='true'
    - php: 5.4
      env: extension='false'
    - php: 5.5
      env: extension='true'
    - php: 5.5
      env: extension='false'
    - php: 5.6
      env: extension='true'
    - php: 5.6
      env: extension='false'
    - php: 7.0
      env: extension='true'
    - php: 7.0
      env: extension='false'
    - php: 7.1
      env: extension='true'
    - php: 7.1
      env: extension='false'    
    - php: 7.2
      env: extension='true'
    - php: 7.2
      env: extension='false'

before_script:
  - php --version
  - mkdir -p $(dirname ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini)
  - touch ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "php-config -> orig"
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ $extension = 'false' ]]; then sed -i.bkp "s/^extension\ =\ mbstring.so$/#extension = mbstring.so/" ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $extension = 'false' ]]; then sed -i.bkp "s/^extension\ =\ intl.so$/#extension = intl.so/" ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $extension = 'false' ]]; then sed -i.bkp "s/^extension\ =\ iconv.so$/#extension = iconv.so/" ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - echo "php-config -> new"
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls:1.0.0
  - travis_retry composer install --no-interaction --prefer-source
  - composer dump-autoload -o

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
